# cloudbuild.yaml for Google Cloud Build
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/bcf-renewable-energy-app', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/bcf-renewable-energy-app']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'run'
    - 'deploy'
    - 'bcf-renewable-energy-app'
    - '--image'
    - 'gcr.io/$PROJECT_ID/bcf-renewable-energy-app'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--set-env-vars'
    - 'FLASK_SECRET_KEY=$$FLASK_SECRET_KEY,ADMIN_PASSWORD=$$ADMIN_PASSWORD'
    - '--memory'
    - '2Gi'
    - '--cpu'
    - '2'
    - '--max-instances'
    - '10'
    - '--timeout'
    - '300'

# Store sensitive environment variables in Google Secret Manager
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/flask-secret-key/versions/latest
    env: 'FLASK_SECRET_KEY'
  - versionName: projects/$PROJECT_ID/secrets/admin-password/versions/latest
    env: 'ADMIN_PASSWORD'